# Site settings
title: My GitHub Pages Site
description: This is a simple GitHub Pages site using a Jekyll theme.
url: "https://robviera.github.io"  # Replace <username> with your GitHub username

# Build settings
# theme: jekyll-theme-slate  # Replace with your desired theme

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Optional settings
markdown: kramdown
kramdown:
  input: GFM
